image: diceengineering/frydom-ce:latest

test:
    before_script:
        # check this out: https://docs.gitlab.com/ee/ci/ssh_keys/
       - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
       - eval $(ssh-agent -s)
       - mkdir -p ~/.ssh
       - echo "$GITLAB_CI_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
       - chmod 700 ~/.ssh
       - chmod 700 ~/.ssh/id_rsa
       - ssh-add
       # also add the known hosts so we don't have to accept when connecting to the host
       - echo "$GITLAB_CI_SSH_KNOWN_HOST" | tr -d '\r' > ~/.ssh/known_hosts


    script:
        - rm -rf build
        - mkdir build
        - cd build
        - cmake -Dfrydom_download_demo_data=OFF ..
        - cmake -Dfrydom_download_demo_data=OFF ..
        - make all test -j4
#    except:
#        - master

pages:
#    stage: deploy
    script:
        - cd docs/api
        - tag=$(python ../../cmake/getversion.py normalized)
        - sed -i "s/GIT_TAG_VERSION/$tag/g" Doxyfile
        - doxygen Doxyfile
        - mv build/html/ ../../public/
    artifacts:
        paths:
            - public
    only:
        - master

theory:
    before_script:
        # check this out: https://docs.gitlab.com/ee/ci/ssh_keys/
       - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
       - eval $(ssh-agent -s)
       - mkdir -p ~/.ssh
       - echo "$GITLAB_CI_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
       - chmod 700 ~/.ssh
       - chmod 700 ~/.ssh/id_rsa
       - ssh-add
       # also add the known hosts so we don't have to accept when connecting to the host
       - echo "$GITLAB_CI_SSH_KNOWN_HOST" | tr -d '\r' > ~/.ssh/known_hosts
    script:
        - cd docs/theory
        - tag=$(python ../../cmake/getversion.py normalized)
        - sed -i "s/GIT_TAG_VERSION/$tag/g" conf.py
        - make html
        - scp -r ./build/html/* frydomusqo@ssh.cluster027.hosting.ovh.net:/homez.363/frydomusqo/theory-guide
    only:
        - develop

