# This makefile is temporary as in the future, frydom building workflow 
# will rely on cmake, just like its submodule chrono

default_target: all_frydom
.PHONY : default_target


#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The command to remove a file.
RM = /bin/rm -f

